config:
  aws:region: us-east-1
  ckp:environment: dev
  ckp:appName: creole-knowledge-portal
  ckp:domainName: ckp.nikcreations.com
  ckp:listenerPriorityBase: "1100"
  ckp:ecsDesiredCount: "1"
  ckp:webDesiredCount: "1"
  ckp:apiDesiredCount: "1"
  ckp:workersDesiredCount: "1"
  ckp:ecsCpu: "1024"
  ckp:ecsMemory: "2048"
  ckp:githubRepo: Creolestudios/creole-knowledge-portal
  ckp:supabaseUrl:
    secure: AAABAKxBrG0h6Cb53g6R44kk9hg+xgdXNLEU5AniJMGFRXqrWpfsonaVdDi0v8FO3bQFxH/bwZt61mg8YgTd3ntjlQz9dGm9
  ckp:supabaseAnonKey:
    secure: AAABACl4f9hyNnte2NJ/Ue3trcWcEXj8+KYI3an0ytYOPb0Es/7KYjDG+4dWRFdbQ+l432HhpKScNxYwQWbH5Z1R2r4sr4Nma4/AGNb8JQezdKvJ6m2JZg924DIKHHNylJECl9ZzbtpSNJ5PSOIL10RuTy8NTlurSBJPG7mfjzbtb8qte7ZLG/vXozhz1U7x9UkxpSRYsofj5oSy6AjZ7rKPNoCPlnt9InDRxQw+VSLl5LZXsQwF9JOEib0XoXtwxGWT4qOlqP9ZJCUS7+EJ0CH+ZKZ0SAvNrBRBiu6kzl40wzFmJQJVKIW/EA0qvRF3
  ckp:supabaseServiceRoleKey:
    secure: AAABAI39Qr09jT+iXu3YvBDsg4mIiA6aGXxUqAKpf7ba4Yf3ZcERBcLsZaGISixy+kMrdcFXTRc67F2I1uENHOW3lhUknuam2GoYoaFGUjvs1iDPtpxIuhAfKlelIyADXWkFcXvrhnC1bdUVSVv/HXuawGJRz5UiTKdojqSYcX+vwPFYtiGvb+9n2n9DIAkx3hc0SqfUvuhAnXqwMNkHpEyUzdyRRiP/o+3gsT65CeNDrYGNrgHisfPXjFX93PE3mE/j3Upl7b6FLf9L5R/mFz0aBRffl6ifctmZYJ/VTOOhx8yUwzzxiLeg5cChouGk4kydl9o/mFhtCFs=
  ckp:geminiApiKey:
    secure: AAABAEkHNPhGJqcWZyW3ZgQvFQtem5qVCQC3I0X+5gGujExedkgGfwfkw1NEkKLlMy5JdwD47MAFJ5KvVw7gv8KowmU9DCI=
  ckp:llmGeminiApiKey:
    secure: AAABAJos+UE/BMc8a0J2fdwDrkcmU4WYppzR4kjEvXW13xtWSa0PzjFNzF6T0+I0Mn9s7dk67WBJM6O/a9McGzG2t7vATGg=
  ckp:mongoUri:
    secure: AAABALFihS6HiZiLVDATIAPYJuXIMwRQNNRIBKKBwE4Gmxtn9zoDgu304hyW6bMFJNeiUYIUsPXMi9oUS7fXnXO6UjwkrYjudt1sdartkhxoqTC7RXenuHFKCAOaSeW7Q4CCCrENAiZYBl/3+v6KW7jTcnnOtMKUzZBbKh+81O0jY84=
  ckp:redisUrl:
    secure: AAABAMrGsuZyvXIKpkSdwz51Vgm51o6VS+Rbw+HkMbe1hn6t5b3JIBqgWd1vvhj5HKMsDnm63QHHCxY3s9vJo5x/+yFhVEzFbmPA5FGxRAlyA2D7skWKnQpfIGmRofnxNM1zh9QKWW3S1ZyFuvb47dlh2O7Ir+Jif5IlnPDv/aIE
  ckp:webImage: 642024554221.dkr.ecr.us-east-1.amazonaws.com/creole-knowledge-portal-web:latest
  ckp:apiImage: 642024554221.dkr.ecr.us-east-1.amazonaws.com/creole-knowledge-portal-api:latest
  ckp:workersImage: 642024554221.dkr.ecr.us-east-1.amazonaws.com/creole-knowledge-portal-workers:latest
